version: '3.8'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n_local
    restart: always
    ports:
      - "5678:5678"
    user: "1000:1000" 
    volumes:
      - n8n_data:/home/node/.n8n
      - /home/biignoisee/Documents/personal/n8n-rag/base:/home/biignoisee/Documents/personal/n8n-rag/base
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false
      - WEBHOOK_URL=http://localhost:5678/
      - NODES_EXCLUDE=[] # <--- Línea que habilita los nodos
      
volumes:
  n8n_data: